create table ih_users (
    nr_sequencia       number generated by default as identity,
    nm_usuario         varchar2(100) not null,
    ds_usuario         varchar2(200) not null,
    ds_email           varchar2(200),
    ds_senha           varchar2(100) not null,
    ie_situacao        varchar2(1) default 'A' not null,
    ie_tipo_usuario    varchar2(1) not null,
    dt_criacao         timestamp default current_timestamp not null,
    dt_atualizacao     timestamp,

    constraint pk_ih_users
        primary key (nr_sequencia),

    constraint uk_ih_users_usuario
        unique (nm_usuario),

    constraint uk_ih_users_email
        unique (ds_email),

    constraint ck_ih_users_situacao
        check (ie_situacao in ('A', 'I')),

    constraint ck_ih_users_tipo
        check (ie_tipo_usuario in ('A', 'C', 'U'))
);

comment on table ih_users is
    'Usuários do Integration Hub';

comment on column ih_users.nr_sequencia is
    'Identificador único do usuário';

comment on column ih_users.nm_usuario is
    'Nome utilizado para login';

comment on column ih_users.ds_usuario is
    'Nome ou descrição do usuário';

comment on column ih_users.ds_email is
    'E-mail do usuário';

comment on column ih_users.ds_senha is
    'Hash BCrypt da senha do usuário';

comment on column ih_users.ie_situacao is
    'Situação do usuário: A=Ativo, I=Inativo';

comment on column ih_users.ie_tipo_usuario is
    'Tipo do usuário: A=Administrador, C=Criador, U=Consumidor';

comment on column ih_users.dt_criacao is
    'Data e hora de criação do usuário';

comment on column ih_users.dt_atualizacao is
    'Data e hora da última atualização';
